accessing
testError: anObject

	testError := anObject