instance creation
withError: anError
	^ self new
		originalError: anError;
		yourself